name: PR health check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build container image
      run: docker build --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') --build-arg BUILD_VERSION=$GITHUB_SHA --build-arg VCS_REF=$GITHUB_SHA -t ulisesgascon/development-toolkit:latest .