name: PR health check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build container image
      run: docker build -t ulisesgascon/development-toolkit:latest .